#Task 1.3: MATH FOR ML
##Dataset
Diabetes Dataset

###Objective
Work through mean, median, variance, standard deviation, covariance, and correlation using small
datasets.


**Mean**

In [1]:
data = [10, 20, 30, 40, 50]

mean = sum(data) / len(data)

print("Mean:", mean)

Mean: 30.0


Mean is the average value of the dataset.

**Median**

In [4]:
import numpy as np

data = [10, 20, 30, 40, 50]

print("Median:", np.median(data))

Median: 30.0


Variance

In [5]:
print("Variance:", np.var(data))

Variance: 200.0


**Standard Deviation**

In [6]:
print("Standard Deviation:", np.std(data))

Standard Deviation: 14.142135623730951


**Covariance**

In [7]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

print(np.cov(x, y))

[[ 2.5  5. ]
 [ 5.  10. ]]


**Correlation**

In [8]:
print(np.corrcoef(x, y))

[[1. 1.]
 [1. 1.]]


Correlation shows how two variables move together. It does not by itself prove causation.

**Probability**

In [9]:
total = 10
favorable = 4

probability = favorable / total

print("Probability:", probability)

Probability: 0.4


**Conditional Probability**

In [10]:
P_A = 0.5
P_B_given_A = 0.8

P_A_and_B = P_A * P_B_given_A

print("P(A and B):", P_A_and_B)

P(A and B): 0.4


**Vector**

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Vector A:", a)
print("Vector B:", b)

Vector A: [1 2 3]
Vector B: [4 5 6]


**Dot Product**

In [12]:
dot_product = np.dot(a, b)

print("Dot Product:", dot_product)

Dot Product: 32


A dot product produces a weighted sum and is commonly used in linear models and neural-network layers.

**Matrix**

In [13]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("A:")
print(A)

print("B:")
print(B)

print("A + B:")
print(A + B)

print("A × B:")
print(np.dot(A, B))

A:
[[1 2]
 [3 4]]
B:
[[5 6]
 [7 8]]
A + B:
[[ 6  8]
 [10 12]]
A × B:
[[19 22]
 [43 50]]


In [14]:
print("Shape of A:", A.shape)
print("Shape of B:", B.shape)

Shape of A: (2, 2)
Shape of B: (2, 2)


**Derivative**

In [15]:
def f(x):
    return x**2

For f(x) = x², the derivative describes how quickly the function changes with respect to x.

**Gradient Descent**

Gradient descent is an optimization method.

Parameters produce a loss.

The gradient tells us the direction of change.

The parameters are then updated to reduce the loss.